keys:
  hosts:
    - &laptop age1zad0qu648dhjav4pzjhkc6vswnqtacuv9230xcgle8wmv56r8ykqn0ud7y
    - &desktop age1rwugh86469664fwhgrj9xuhjxs9vpflx3r0ftuvd0glphf2gecfs8thxsj
    - &virtual age1q5zwds8g47j7xsqhp8tk995l3n4a5z876vff7wgx4sztwgdsa3yq7eu6xk
creation_rules:
  - path_regex: '.*/secrets/[^/]+\.(yaml|json|env|ini)$'
    key_groups:
      - age:
          - *laptop
          - *desktop
          - *virtual
