keys:
  hosts:
    - &laptop age1ldgnl53dmvl4fjz6hgdj0cvensagddn3ltpmxfm72m8q273w75fsk42p8v
    - &nixos-homelab-00 age1k0m6kf456wg6qgxk7em6dhswe47vwnv3zs4ajjrhmy0sfkealcls5xv5la
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *laptop
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
