keys:
  hosts:
    - &laptop age1ldgnl53dmvl4fjz6hgdj0cvensagddn3ltpmxfm72m8q273w75fsk42p8v
    - &nixos-homelab-00 age177wwag0rmyejqm37l748tuup5lvdslaza6kjkrjhdfce2drajscqn6cmru
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *laptop
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
          - *nixos-homelab-00
